name: Gradle CI

on: [push, create]
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11 ]
        mongodb-version: [ 4.0, 4.2, 4.4 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Build
      if: github.event_name == 'push'
      run: ./gradlew build
    - name: Build for release [tag only]
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: sed "s/0.0.0/$TAG/g" build.gradle.kts > _build.gradle.kts && mv _build.gradle.kts build.gradle.kts &&./gradlew build -x jar
      env:
        TAG: ${{github.event.ref}}
    - name: Create GitHub release [tag only]
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: |
        curl --data $'{"tag_name":"${{github.event.ref}}","target_commitish": "master","name": "${{github.event.ref}}","body": "Release ${{github.event.ref}}","draft": false,"prerelease": true}' https://api.github.com/repos/$GITHUB_REPOSITORY/releases?access_token=$GITHUB_TOKEN
        RELEASE_ID=$(curl https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{github.event.ref}}?access_token=$GITHUB_TOKEN | jq '.id')
        echo "Release id: $RELEASE_ID"
        sleep 10
        for filename in build/libs/*; do curl --data-binary "@$filename" -H "Content-Type: application/java-archive" "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID/assets?name=$(basename $filename)&access_token=$GITHUB_TOKEN" ; done
    - name: Upload to test server [tag only]
      if: github.repository == 'colin-bz/labpipe-server-public' && github.event_name == 'create' && github.event.ref_type == 'tag'
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.LABPIPE_TEST_HOST}}
        username: ${{secrets.LABPIPE_TEST_SERVER_USER}}
        password: ${{secrets.LABPIPE_TEST_SERVER_CREDENTIAL}}
        source: "build/libs/labpipe-server-${{github.event.ref}}.jar"
        target: "/local/apps/labpipe"
        strip_components: 2
    - name: Deploy to test server [tag only]
      if: github.repository == 'colin-bz/labpipe-server-public' && github.event_name == 'create' && github.event.ref_type == 'tag'
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.LABPIPE_TEST_HOST}}
        username: ${{secrets.LABPIPE_TEST_SERVER_USER}}
        password: ${{secrets.LABPIPE_TEST_SERVER_CREDENTIAL}}
        script: |
          cd /local/apps/labpipe
          screen -S labpipe -X quit
          screen -S labpipe -d -m java -jar labpipe-server-${{github.event.ref}}.jar run
          
